DOMAIN = "nordpool_planner"

CONF_NAME = "name"
CONF_TYPE = "type"
CONF_TYPE_MOVING = "moving"
CONF_TYPE_STATIC = "static"
CONF_TYPE_LIST = [CONF_TYPE_MOVING, CONF_TYPE_STATIC]
CONF_NP_ENTITY = "np_entity"
CONF_DURATION = "duration"
CONF_DURATION_ENTITY = "duration_entity"
CONF_ACCEPT_COST = "accept_cost"
CONF_ACCEPT_COST_ENTITY = "accept_cost_entity"
CONF_ACCEPT_RATE = "accept_rate"
CONF_ACCEPT_RATE_ENTITY = "accept_rate_entity"
CONF_SEARCH_LENGTH = "search_length"
CONF_SEARCH_LENGTH_ENTITY = "search_length_entity"
CONF_END_TIME = "end_time"
CONF_END_TIME_ENTITY = "end_time_entity"
